name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (for testing or other setup)
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run tests
      run: |
        # Example test: Check if hello.html exists
        if [ ! -f hello.html ]; then
          echo "hello.html file does not exist"
          exit 1
        else
          echo "hello.html file exists"
        fi

    - name: Deploy
      run: |
        echo "Deploying hello.html to the web server..."
        # Example deployment command
        # Replace with actual deployment commands or scripts
        scp hello.html user@yourserver:/path/to/deploy/
